
<div class="page">
		<section class="register">
			<div class="form-container">
				<form method="POST">
					<h2 class="text-center"><strong>Create</strong> an account.</h2>

					<?php if ($err_message) : ?>
						<div class="callout text-danger">
							<p><?php echo $err_message; ?></p>
						</div>
					<?php endif; ?>
					
					<div class="mb-3"><input class="form-control" type="tel" id="phone" name="phone" placeholder="Phone Number" value="<?php echo ((isset($_POST['tel'])) ? $_POST['tel'] : ''); ?>" required></div>
					<span id="valid-msg" class="hide">✓ Valid</span>
					<span id="error-msg" class="hide"></span>
					
					<div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit" name="telsign" required>Sign Up</button></div><a class="already" href="signin.php">Already have an account? Sign in here.</a>
				</form>
			</div>
		</section>
	</div>